### ISSUE TITLE
Tile Grouping

### ISSUE THREAD

**Issue by GreyMatteOr** [GreyMatteOr/puzzlooza-host#10]
I don't know how easy it is to do, but I would love if we could just combine the 2 pieces somehow in a single html element. This might be possible, it might not. It also may be easy with squares, but I'm curious about joining mismatched shapes. I would love to try, if it looks at all possible ( I think the experience would feel much better ). 

If it's not possible, though, we should either think this should be a 'Group' class, where tiles all have a relative position in the group and moving any piece of the group moves the entire group.

If all of this seems too complex, we may need to code in a grid system ( which I know we can do, although I really don't want to. It just feels way worse to have things rigidly defined)

Remember whatever we decide, it will have to be workable with concurrent players / sockets.

**Comment by BlakeDonn** [comment]
Could you elaborate on `combine the 2 pieces somehow in a single html element.` 
Would these be two pieces that the user has matched, and by extension could continue matching new ones on to? Just want to make sure I understand correctly.

If so, I definitely like the idea of joining them into one, though am unsure about the logistics behind this.

**Comment by GreyMatteOr** [comment]
Full disclosure: at the time of writing,  I am decently ignorant to the full capabilities of `Canvas` elements, so there are some big assumptions about what is possible using them. The couple ways imagined:

## 1.)

On load, we receive the picture. We then (somehow) divide it up and create `html` elements that contain only a small piece of the picture that it displays. These might be elements unique to `canvas`es, or perhaps merely `div`s? Then, when two tiles that represent a match are `snapped` together, they somehow create a new element that consists of their previous contents and then delete themselves. Continue until the entire puzzle is contained in a single element

## 2.)
Very similar to the previous way, but we keep a copy of the original picture and reference each tile to a portion of the image using a unique id. We can use the id to get the section of the picture at will. This way, when two elements `match` they give up their id's, and then delete themselves and we a new super element containing the two.

**Comment by GreyMatteOr** [comment]
<img width="696" alt="Screen Shot 2020-11-18 at 11 57 38 AM" src="https://user-images.githubusercontent.com/65369751/99581206-4b973a00-2995-11eb-87dc-f9e2d6bc7a5c.png">

**Comment by GreyMatteOr** [comment]
Now that we have movement somewhat more concrete, I've given some thought to what this might look like.
<img width="684" alt="Screen Shot 2020-11-20 at 8 31 44 AM" src="https://user-images.githubusercontent.com/65369751/99824636-d483b200-2b0a-11eb-855b-2c78306d99f6.png">
<img width="397" alt="Screen Shot 2020-11-20 at 8 32 15 AM" src="https://user-images.githubusercontent.com/65369751/99824691-e6fdeb80-2b0a-11eb-8c7f-25e4d1e2b71c.png">

**Comment by GreyMatteOr** [comment]
<img width="563" alt="Screen Shot 2020-11-25 at 12 12 44 PM" src="https://user-images.githubusercontent.com/65369751/100277155-89590d00-2f17-11eb-93c7-1c216ff621f8.png">

**Comment by GreyMatteOr** [comment]
<img width="542" alt="Screen Shot 2020-11-25 at 12 13 21 PM" src="https://user-images.githubusercontent.com/65369751/100277200-9f66cd80-2f17-11eb-9760-8dc66d336992.png">
