### ISSUE TITLE
Tile Snapping / Locking

### ISSUE THREAD

**Issue by GreyMatteOr** [GreyMatteOr/puzzlooza-host#11]
Need to cement how we want to join tiles together.
- [ ] Should they snap to everything or only when correct?
- [ ] Should the lock by default? Or only when correct? Or on user click? Can a user undo it?
- [ ] What is the impact of the snapping on the receiving tile? Should it be raised to the front as well? Other considerations?
- [ ] What is a good snap range? How do we scale that for accessibility?

**Comment by BlakeDonn** [comment]
I think we really need to get the basis for our validation system sorted out, how do we tell which sides are compatible ? Do we only validate when a user deems the board complete, or on a piece-by-piece basis? 

I am in favor of a piece-by-piece basis if we can develop the tech for it, some rough ideas to start...
1. When the image is initially split, assign unique values for each side of every piece which will be our source of truth
2. When a user attempts to snap tiles together, our validation functionality will run and either snap (correct) or visually push back (incorrect)

I don't know if this is maybe too ambitious or not, it's hard to tell without getting too deep into it.

**Comment by GreyMatteOr** [comment]
I like this idea. I had worked out something similar.

I think it's smart to prioritize such a key part, so let work on this as soon as we can.
