### ISSUE TITLE
Tile Validation

### ISSUE THREAD

**Issue by GreyMatteOr** [GreyMatteOr/puzzlooza-host#12]
How do we want to check if 2 tiles are a match? This should be decently easy to implement, but we have several options and we should be intentional about which we choose.

- Should the validation be done by a data structure that contains all the Tile data?
- Should the tiles keep the information for their own match?
- How do we ID tiles? Should each side of a tile have a unique id? should each connection have a unique id?
- Should a tile have a `correct` orientation that we should track? 
- How will edge-tiles be marked?
- When a tile is entering a group, what's our system of validation? Only one match is sufficient? 

Let's draw a flow chart for the system

**Comment by BlakeDonn** [comment]
`When a tile is entering a group, what's our system of validation? Only one match is sufficient?`

This is a really tricky point, it seems like we would need multiple forms of validation to avoid a user getting a false positive for a bad grouping. But then again, could we strictly use side-validation for this? No matter what, if the sides are uniquely approved, then by default the group would be considered valid?

I will think more on this, as to not over-simplify, but it seems if we use a strict-side-based-validation system we can alleviate a lot of the bigger problems. If the tiles are compatible, we can assume the grouping is valid. The tricky part will be how we assign the sides the unique value

**Comment by GreyMatteOr** [comment]
Here's an example of one possiblie way to do this. I was thinking a 3x3 might resemble something like this:   
```
     + : is a tile
     
     T.id
 L.id  +  R.id            
     B.id

   null null null
null + 1 + 2 + null
     3   4   5
null + 6 + 7 + null
     8   9   10
null + 11+12 + null
   null null null
```
Then we if we check which sides are trying to match and they are the same, then it's a match! 

There would have to be some logic to get which sides are being compared, but I think each element will have a `position` property with an x, y coordinate we can use to figure that out. 

I think this puts all the difficulty on the initial separation, and makes it decently easy to reason about. There may be some small adjustments when we 'snap' things, but again depending how we choose to implement, maybe not.

**Comment by GreyMatteOr** [comment]
Boy this is terribly hard to read, isn't it!?

🤦

**Comment by BlakeDonn** [comment]
The map looks good to me!

**Comment by GreyMatteOr** [comment]
<img width="920" alt="Screen Shot 2020-11-18 at 8 49 37 AM" src="https://user-images.githubusercontent.com/65369751/99560697-02d28780-297b-11eb-8304-4dd2af2d1934.png">
<img width="920" alt="Screen Shot 2020-11-18 at 8 50 26 AM" src="https://user-images.githubusercontent.com/65369751/99560791-1c73cf00-297b-11eb-9793-a84c3122c2b3.png">
<img width="920" alt="Screen Shot 2020-11-18 at 8 51 00 AM" src="https://user-images.githubusercontent.com/65369751/99560858-31506280-297b-11eb-9ec7-6701beb4ec7c.png">

**Comment by GreyMatteOr** [comment]
This is actually got some amazing implied state. When we introduce tile-rotating, we want to know that it's `oriented` correctly.

Based on this, the top has to be the lowest MatchID, and the left has to be the second lowest, right is 3rd, bottom is biggest. If these aren't true, then the tile isn't `rotated` correctly, so this actually has some nice implicit functionality we might use in the future.

**Comment by BlakeDonn** [comment]
This is a fantastic write up, the logic seems really strong for keeping things consistent. I don't really have any questions regarding this and may start to mock up some functionality to test it out.
