### ISSUE TITLE
Tile Movement

### ISSUE THREAD

**Issue by GreyMatteOr** [GreyMatteOr/puzzlooza-host#9]
Bring in `dragmove.js`

- [x] Be able to drag the tiles
- [x] Figure out a solution for overlapping tiles. Possible ideas:
  - Have the most recent tile moved jump to the top ? 
  - Have tiles get partially / totally pushed away when other tiles overlap them ?
  - Have a gridded layout ? Swap the 2 pieces involved ?
  - other

**Comment by BlakeDonn** [comment]
My initial feeling is to go for the pushing away when tiles overlap, I think overall this would keep the board more clean and would alleviate any need to overlap / favor pieces.

It does seem like dragmove.js overlaps by default? I don't have any experience with it but will check out some documentation

**Comment by GreyMatteOr** [comment]
[Link](https://github.com/knadh/dragmove.js) to `dragmove.js`

<img width="1058" alt="Screen Shot 2020-11-18 at 11 01 43 AM" src="https://user-images.githubusercontent.com/65369751/99575415-754c6300-298d-11eb-8dc7-1addf688ca12.png">

**Comment by GreyMatteOr** [comment]
Update to Overlap Write-up
<img width="708" alt="overlap-writeup" src="https://user-images.githubusercontent.com/65369751/99772505-c492b080-2abf-11eb-93a9-9e6565365fb3.png">

**Comment by GreyMatteOr** [comment]
I've solved the bulk of this issue with my last push. Some remaining edge-cases:

- How do we handle the edge of the window? There is a toggle-property that prevents screen 'Out-of-bounding', and I think the current propogation-strategy should solve it, but we do need to implement it, if that's what we choose.

- As tile groupings get larger, we do need to make sure that none of the functionality breaks. (we may need to massage the algorithm a bit to possibly allow some overlap)

**Comment by GreyMatteOr** [comment]
<img width="673" alt="Screen Shot 2020-11-19 at 11 39 37 PM" src="https://user-images.githubusercontent.com/65369751/99772909-7f22b300-2ac0-11eb-82cf-0d51d378f07f.png">
